# Generated by Django 5.2.7 on 2025-10-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreferenceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, help_text='How many times this tag appeared in orders')),
            ],
            options={
                'db_table': 'customerpreferencetag',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ordertime', models.DateTimeField(auto_now_add=True)),
                ('isrecommended', models.BooleanField(default=False, help_text='Was this AI-recommended?')),
                ('aiexplanation', models.TextField(blank=True, help_text="Claude's recommendation reasoning")),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-ordertime'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'orderitem',
            },
        ),
    ]
